services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/gateway/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
      - netdata
    networks:
      - dmz

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    networks:
      - dmz

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NETDATA_URL=http://netdata:19999
      - PORT=3001
    networks:
      - dmz

  netdata:
    image: netdata/netdata:stable
    networks:
      - dmz

networks:
  dmz:
    driver: bridge